apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cesydb8xx-dotnet-basic
  janus-idp.io/tekton: cesydb8xx-dotnet-basic
  backstage.io/kubernetes-id: cesydb8xx-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cesydb8xx-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
